version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: H4ckM3IfYoUC4n
      MYSQL_DATABASE: backend_test
      MYSQL_USER: zakir
      MYSQL_PASSWORD: zakir1337
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/database.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: H4ckM3IfYoUC4n
    ports:
      - "8080:80"
    depends_on:
      - mysql

volumes:
  mysql_data:
